create table if not exists public.inventario (
  id bigint generated by default as identity primary key,
  clave text not null unique,
  producto text not null,
  categoria text not null default 'Otros',
  medida text not null default '',
  variante text not null default '',
  cantidad numeric not null check (cantidad >= 0),
  unidad text not null default '',
  observaciones text not null default '',
  ubicacion text not null default 'Pasillo' check (ubicacion in ('Pasillo', 'Galpón', 'Nonna')),
  precio_min numeric,
  precio_referencia numeric,
  precio_max numeric,
  moneda text not null default 'ARS',
  fuentes_precio jsonb not null default '[]'::jsonb,
  precio_confianza text,
  precio_actualizado_en timestamptz,
  actualizado_en timestamptz not null default now()
);

-- Actualiza proyectos creados antes de incorporar la categoría.
alter table public.inventario
  add column if not exists categoria text not null default 'Otros';

alter table public.inventario enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.inventario to service_role;
grant usage, select on sequence public.inventario_id_seq to service_role;

-- La aplicación usa SUPABASE_SERVICE_KEY guardada como secreto del servidor.
-- No crear políticas públicas para esta tabla.

create table if not exists public.cargas_inventario (
  id bigint generated by default as identity primary key,
  huella text not null,
  estado text not null default 'activa'
    check (estado in ('activa', 'deshecha', 'error')),
  creado_en timestamptz not null default now(),
  deshecho_en timestamptz,
  imagenes jsonb not null default '[]'::jsonb
);

create index if not exists cargas_inventario_huella_idx
  on public.cargas_inventario (huella, estado);

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  carga_id bigint not null references public.cargas_inventario(id)
    on delete cascade,
  clave text not null,
  producto text not null,
  categoria text not null default 'Otros',
  medida text not null default '',
  variante text not null default '',
  cantidad_agregada numeric not null check (cantidad_agregada > 0),
  unidad text not null default '',
  observaciones text not null default '',
  creado_en timestamptz not null default now()
);

create index if not exists movimientos_inventario_carga_idx
  on public.movimientos_inventario (carga_id);

alter table public.cargas_inventario enable row level security;
alter table public.movimientos_inventario enable row level security;

grant select, insert, update, delete
  on table public.cargas_inventario to service_role;
grant select, insert, update, delete
  on table public.movimientos_inventario to service_role;
grant usage, select on sequence public.cargas_inventario_id_seq to service_role;
grant usage, select on sequence public.movimientos_inventario_id_seq to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'inventario-fotos',
  'inventario-fotos',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.inventario
  add column if not exists precio_min numeric,
  add column if not exists precio_referencia numeric,
  add column if not exists precio_max numeric,
  add column if not exists moneda text not null default 'ARS',
  add column if not exists fuentes_precio jsonb not null default '[]'::jsonb,
  add column if not exists precio_confianza text,
  add column if not exists precio_actualizado_en timestamptz;

alter table public.inventario
  drop constraint if exists inventario_precios_no_negativos;

alter table public.inventario
  add constraint inventario_precios_no_negativos check (
    (precio_min is null or precio_min >= 0)
    and (precio_referencia is null or precio_referencia >= 0)
    and (precio_max is null or precio_max >= 0)
  );

-- Guardado atómico: si falla una operación, se revierte todo el lote.
create or replace function public.aplicar_lote_atomico(
  p_carga_id bigint,
  p_productos jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_carga_id is null
     or p_productos is null
     or jsonb_typeof(p_productos) <> 'array' then
    raise exception 'Datos del lote inválidos';
  end if;

  insert into movimientos_inventario (
    carga_id, clave, producto, categoria, medida, variante,
    cantidad_agregada, unidad, observaciones, ubicacion
  )
  select
    p_carga_id,
    x.clave,
    coalesce(x.producto, ''),
    coalesce(x.categoria, 'Otros'),
    coalesce(x.medida, ''),
    coalesce(x.variante, ''),
    x.cantidad,
    coalesce(x.unidad, ''),
    coalesce(x.observaciones, ''),
    coalesce(x.ubicacion, 'Pasillo')
  from jsonb_to_recordset(p_productos) as x(
    clave text,
    producto text,
    categoria text,
    medida text,
    variante text,
    cantidad numeric,
    unidad text,
    observaciones text,
    ubicacion text
  );

  insert into inventario (
    clave, producto, categoria, medida, variante,
    cantidad, unidad, observaciones, ubicacion
  )
  select
    x.clave,
    max(coalesce(x.producto, '')),
    max(coalesce(x.categoria, 'Otros')),
    max(coalesce(x.medida, '')),
    max(coalesce(x.variante, '')),
    sum(x.cantidad),
    max(coalesce(x.unidad, '')),
    max(coalesce(x.observaciones, '')),
    max(coalesce(x.ubicacion, 'Pasillo'))
  from jsonb_to_recordset(p_productos) as x(
    clave text,
    producto text,
    categoria text,
    medida text,
    variante text,
    cantidad numeric,
    unidad text,
    observaciones text
  )
  group by x.clave
  on conflict (clave) do update
  set cantidad = inventario.cantidad + excluded.cantidad,
      ubicacion = excluded.ubicacion,
      actualizado_en = now();
end;
$$;

revoke all on function public.aplicar_lote_atomico(bigint, jsonb)
from public;

grant execute on function public.aplicar_lote_atomico(bigint, jsonb)
to service_role;
