create table if not exists public.inventario (
  id bigint generated by default as identity primary key,
  clave text not null unique,
  producto text not null,
  categoria text not null default 'Otros',
  medida text not null default '',
  variante text not null default '',
  cantidad numeric not null check (cantidad >= 0),
  unidad text not null default '',
  observaciones text not null default '',
  actualizado_en timestamptz not null default now()
);

-- Actualiza proyectos creados antes de incorporar la categoría.
alter table public.inventario
  add column if not exists categoria text not null default 'Otros';

alter table public.inventario enable row level security;

-- La clave secreta del servidor omite RLS, pero igualmente necesita privilegios SQL.
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.inventario to service_role;
grant usage, select on sequence public.inventario_id_seq to service_role;

-- La aplicación usa SUPABASE_SERVICE_KEY guardada como secreto del servidor.
-- No crear políticas públicas para esta tabla.

-- Historial de cada lote confirmado.
create table if not exists public.cargas_inventario (
  id bigint generated by default as identity primary key,
  huella text not null,
  estado text not null default 'activa'
    check (estado in ('activa', 'deshecha', 'error')),
  creado_en timestamptz not null default now(),
  deshecho_en timestamptz,
  imagenes jsonb not null default '[]'::jsonb
);

create index if not exists cargas_inventario_huella_idx
  on public.cargas_inventario (huella, estado);

-- Detalle de los productos y cantidades incorporados por cada lote.
create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  carga_id bigint not null references public.cargas_inventario(id)
    on delete cascade,
  clave text not null,
  producto text not null,
  categoria text not null default 'Otros',
  medida text not null default '',
  variante text not null default '',
  cantidad_agregada numeric not null check (cantidad_agregada > 0),
  unidad text not null default '',
  observaciones text not null default '',
  creado_en timestamptz not null default now()
);

create index if not exists movimientos_inventario_carga_idx
  on public.movimientos_inventario (carga_id);

alter table public.cargas_inventario enable row level security;
alter table public.movimientos_inventario enable row level security;

grant select, insert, update, delete
  on table public.cargas_inventario to service_role;
grant select, insert, update, delete
  on table public.movimientos_inventario to service_role;
grant usage, select
  on sequence public.cargas_inventario_id_seq to service_role;
grant usage, select
  on sequence public.movimientos_inventario_id_seq to service_role;

-- Agrega soporte de fotos a instalaciones existentes.
alter table public.cargas_inventario
  add column if not exists imagenes jsonb not null default '[]'::jsonb;

-- Bucket privado: las imágenes se leen solamente desde el servidor de la app.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'inventario-fotos',
  'inventario-fotos',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

