create table if not exists public.inventario (
  id bigint generated by default as identity primary key,
  clave text not null unique,
  producto text not null,
  medida text not null default '',
  variante text not null default '',
  cantidad numeric not null check (cantidad >= 0),
  unidad text not null default '',
  observaciones text not null default '',
  actualizado_en timestamptz not null default now()
);

alter table public.inventario enable row level security;

-- La aplicación usa SUPABASE_SERVICE_KEY guardada como secreto del servidor.
-- No crear políticas públicas para esta tabla.
